import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/app/Header/Header";
import Footer from "@/components/app/Footer/Footer";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app/Sidebar/AppSidebar";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import  {Session}  from "./SessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background `}
        >
        {/* <Session> */}
        <StoreProvider>
          <SidebarProvider>
            <div className="md:hidden">
              <AppSidebar />
            </div>
            <main className="w-full">
              <Header />
              {children}
              <Toaster richColors/>
              <Footer />
            </main>
          </SidebarProvider>
        </StoreProvider>
        {/* </Session> */}
      </body>
    </html>
  );
}
